[general]
output = "numucc_incl"

[[sample]]
name = "simulation"
path = "/pnfs/sbnd/scratch/users/mueller/v10_06_00/bnb/sbnd_bnbrockbox_v10_06_00_test.flat.root"
ismc = true

[[tree]]
name = "selected1muX"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "containment_cut", type = "reco"},
    {name = "valid_flashmatch", type = "reco"},
    {name = "no_photons", type = "reco", parameters = [25.0,]},
    {name = "no_electrons", type = "reco", parameters = [25.0,]},
    {name = "no_charged_pions", type = "reco", parameters = [25.0,]},
    {name = "single_muon", type = "reco", parameters = [143.425,]},
    {name = "single_proton", type = "reco", parameters = [50.0,]}
]
branch = [
    {name = "neutrino_id", type = "true"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "pdg", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "flash_time", type = "reco"}
]

[[tree]]
name = "signal1mu1p"
sim_only = true
mode = "true"
cut = [
    {name = "neutrino", type = "true"},
    {name = "fiducial_cut", type = "true"},
    {name = "containment_cut", type = "true"},
    {name = "no_photons", type = "true", parameters = [25.0,]},
    {name = "no_electrons", type = "true", parameters = [25.0,]},
    {name = "no_charged_pions", type = "true", parameters = [25.0,]},
    {name = "single_muon", type = "true", parameters = [143.425,]},
    {name = "single_proton", type = "true", parameters = [50.0,]}
]
branch = [
    {name = "neutrino_id", type = "true"},
    {name = "category", type = "true"},
    {name = "visible_energy", type = "both"},
    {name = "fiducial", type = "reco"},
    {name = "containment", type = "reco"},
    {name = "flash_time", type = "reco"},
    {name = "photon_multiplicity", type = "reco", parameters = [25.0,]},
    {name = "electron_multiplicity", type = "reco", parameters = [25.0,]},
    {name = "muon_multiplicity", type = "reco", parameters = [25.0,]},
    {name = "pion_multiplicity", type = "reco", parameters = [143.425,]},
    {name = "proton_multiplicity", type = "reco", parameters = [50.0,]},
]