
[[this_includes]]
file = '/exp/sbnd/app/users/brindenc/develop/medulla_area/medulla/spineplot/configurations/analyses/sbnd/numu_incl2025_sbnd_variables.toml'

[[this_includes]]
file = '/exp/sbnd/app/users/brindenc/develop/medulla_area/medulla/spineplot/configurations/common/styles.toml'

[samples]
[samples.mc_nu]
key = 'simulation'
exposure_type = 'pot'
trees = ['selected1muXNu']
precompute = { reco_leading_muon_momentum_gev = "reco_leading_muon_momentum / 1000.0"}
print_sys = true
systematics = ['multisimTree','multisigmaTree']

[samples.mc_cos]
key = 'simulation'
exposure_type = 'pot'
trees = ['selected1muXCos']
precompute = { reco_leading_muon_momentum_gev = "reco_leading_muon_momentum / 1000.0"}

[output]
path = '/exp/sbnd/data/users/brindenc/medulla/test/tmp'

[analysis]
ordinate_sample = 'data'
category_branch = 'true_category'
category_assignment = [[0], [1], [2,3], [4], [5], [6], [7], [-1]]
category_labels = ['$\nu_\mu$ CC (cont.)', '$\nu_\mu$ CC (exit)', '$\nu_\mu$ CC (OOPS)', 'Non-AV', '$\nu_e$ CC', 'NC', 'Cosmic', 'Data']
category_colors = ['gold','goldenrod','purple','sienna','blue','green','red', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[samples.data]
key = 'data'
exposure_type = 'pot'
override_category = -1
trees = ['selected1muXNu']
precompute = { reco_leading_muon_momentum_gev = "reco_leading_muon_momentum / 1000.0"}

[[systematic_recipe]]
name = 'flux'
label = 'Flux Systematics'
pattern = 'Flux'

[[systematic_recipe]]
name = 'multisim_xsec'
label = 'Interaction Systematics: Multisim'
pattern = 'GENIEReWeight_SBN_v1_multisim_(ZExpAVariation|CCRES|NCRES|NCELVariation|DISBY|FSI)+'

[[systematic_recipe]]
name = 'multisigma_xsec'
label = 'Interaction Systematics: Multisigma'
pattern = 'GENIEReWeight_SBN_v1_multisigma_(VecFFCCQEshape|RPA_CCQE|CoulombCCQE|NormCCMEC|NormNCMEC|RDec|Theta|NormCCCOH|NormNCCOH|NonRES)+'

[[systematic_recipe]]
name = 'interaction'
label = 'Interaction Systematics'
pattern = '(multisim|multisigma)_xsec'

[[systematic_recipe]]
name = 'stats'
label = 'Statistical Uncertainty'
pattern = '(mc_nu|mc_cos|offbeam)_statistical'

[[systematic_recipe]]
name = 'all'
label = 'Total MC Uncertainty'
pattern = '(flux|interaction|stats)'

[[figure]]
name = 'reco_leading_muon_costheta'
type = 'SimpleFigure'
style = 'selected_sbnd'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_costheta'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false, 'draw_error' = 'all'}

[[figure]]
name = 'reco_leading_muon_momentum'
type = 'SimpleFigure'
style = 'selected_sbnd'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_leading_muon_momentum'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false, 'draw_error' = 'all'}
