
[[this_includes]]
file = '/exp/sbnd/app/users/brindenc/develop/medulla_area/medulla/spineplot/configurations/common/variables.toml'

[[this_includes]]
file = '/exp/sbnd/app/users/brindenc/develop/medulla_area/medulla/spineplot/configurations/common/styles.toml'

[samples]
[samples.mc]
key = "simulation"
exposure_type = "pot"
trees = ['selected1mu1p','signal1mu1p']

[output]
path = '/exp/sbnd/data/users/brindenc/medulla/test/tmp'

[analysis]
ordinate_sample = 'mc'
category_branch = 'category'
category_assignment = [[0,2], [1,3,4,5,6], [7], [-1,8]]
category_labels = ['1$\mu$Np', 'Other CC $\nu$', 'NC $\nu$', 'Cosmic']
category_colors = ['C0', 'C1', 'C3', 'C4', 'black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram']

[[figure]]
name = 'reco_edep'
type = 'SimpleFigure'
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_visible_energy'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = false}
