[analysis]
ordinate_sample = 'onbeam'
category_branch = 'category'
category_assignment = [[0,2], [1,3,4,5], [6], [-1,7], [-100]]
category_labels = ['1$\mu$Np', 'Other CC $\nu$', 'NC $\nu$', 'Cosmic', 'Run 2 Data']
category_colors = ['C0', 'C1', 'C3', 'C4', 'C2']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[samples]
[samples.mc]
key = "mc"
scaling_type = "pot"

[samples.offbeam]
key = "offbeam"
scaling_type = "pot"

[samples.onbeam]
key = "onbeam"
scaling_type = "pot"
override_category = -100

[styles]
[styles.selected]
style_sheet = "styles/muon2024.mplstyle"
show_component_number = true
show_component_percentage = true
invert_stack_order = false

[variables]
[variables.visible_energy]
key = "reco_edep"
range = [0, 3]
nbins = 25
xlabel = "Visible Energy [GeV]"

[variables.reco_muon_z]
key = "reco_muon_z"
range = [-100, 100]
nbins = 100
xlabel = "Reconstructed Muon End Point Z [cm]"

[spectra]
[spectra.test]
style = 'selected'
variable = 'visible_energy'