[variables]

[variables.true_visible_energy]
key = "true_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "True Visible Energy [GeV]"

[variables.reco_visible_energy]
key = "reco_visible_energy"
range = [0, 3]
nbins = 25
xlabel = "Reconstructed Visible Energy [GeV]"

[variables.true_dpT]
key = "true_dpT"
range = [0,1200]
nbins = 25
xlabel = 'True $\delta p_T$ [MeV/c]'

[variables.reco_dpT]
key = "reco_dpT"
range = [0,1200]
nbins = 25
xlabel = 'Reconstructed $\delta p_T$ [MeV/c]'